### ISSUE TITLE
Privaten konstruktor razreda

### ISSUE THREAD

**Issue by serhio-w03** [veG3ab/ArraysKvadrat#9]
Gospoda. Tole kar delamo je utility class. Se pravi, da bodo vse metode public+static, vse potrebne podatke za izvajanje metod zagotavljamo s parametri. Se pravi, da bomo metode vedno klicali tako, da NIKOLI ne bomo naredili razreda. Ker NOČEMO, da kdo kdaj naredi objekt iz tega tipa, se zavarujemo tako, da naredimo (ponavadi privzeti) konstruktor PRIVATEN.

ker so vsi podatki vedno podani s parametrom, ne potrebujemo podatkov iz objekta, da metodo izvedemo, ....

tale issue je splošen, spremenjeno je bilo v objavi (commitu) : https://github.com/veG3ab/ArraysKvadrat/commit/bf8799686f18993cd43335c29bbed9bf77cc8270

prosil bi, da nekdo od članov tole prevzame (desno: Assignee - assign yourself), popravi in 'issue' zapre (spodaj:close isssue).

**Comment by LukaZnidarsic** [comment]
Po domače, hočete da spremenimo vrstico
public ArraysKvadrat() {
v
private ArraysKvadrat() {
in to je to?
Nisem prepričan, če vas prav razumem zato bom pustil issue odprt.

**Comment by serhio-w03** [comment]
da, naredite privatnega. Sicer pa si lahko pogledate source razreda Arrays (http://www.docjar.com/html/api/java/util/Arrays.java.html, vrstice 55-60), boste videli, da so naredili enako.
